#ifndef POSE_CONSTANTS_HPP
#define POSE_CONSTANTS_HPP

#define LVT_REPROJECTION_TH2 5.991
#define LVT_N_MAP_POINTS 250
#define LVT_ROW_MATCHING_VERTICAL_SEARCH_RADIUS 2
#define LVT_HASHING_CELL_SIZE 25
#define LVT_CORNERS_LOW_TH 200
#define LVT_N_MATCHES_TH 50

#endif
